w3geo/bml-fast

src/components/TheSchlagInfoPanel.vue, src/composables/useSchlag.js, src/constants.js, src/views/MapView.vue
Dieser Pull Request fügt Schlag-Info hinzu, und macht die Schläge in der Karte klickbar.
=> Display schlag info and allow schlag selection

package.json
Ergänzt --host beim npn run dev command
=> Updates npm run dev

src/components/TheEntryForm.vue, src/components/TheEntryList.vue, src/components/TheFertilizerBalance.vue, src/composables/useDataEntries.js, src/composables/useSchlag.js, src/views/MapView.vue
Dieser PR implementiert eine erste, grundsätzliche UI-Logik
=> Basisversion

install/csv2json.js, package.json
Dieser PR erweitert das CSV-Installations-Script und fügt "npm run data" zur package.json
=> update package.json / update data script

package-lock.json, package.json, src/App.vue, src/components/TheEntryForm.vue, src/components/TheEntryList.vue, src/components/TheFertilizerBalance.vue, src/components/TheLoadSavePanel.vue, src/composables/useDataEntries.js, src/views/MapView.vue
Dieser PR fügt Export / Import Funktionalität hinzu und verbessert das Styling
=> Load save data

src/components/TheEntryForm.vue, src/components/TheLoadSavePanel.vue
Dieser PR unterzieht das Eingabeformular einem Styling inkl. besserer farblicher Gruppierung der Elemente der Fruchtfolge.
=> Styling of entryform

src/components/TheEntryForm.vue, src/components/TheFertilizerBalance.vue, src/composables/useDataEntries.js, src/composables/useLookUps.js
Dieser PR implementiert erste Logiken zur Bilanzberechnung und einige kleine Änderungen und Bugfixes gemäß dem Meeting vom 18.09.24
=> Bilanz first steps

src/components/TheEntryForm.vue, src/components/TheEntryList.vue, src/components/TheFertilizerBalance.vue, src/composables/useDataEntries.js, src/composables/useLookUps.js
Diese Version finalisiert das Eingabeformular für die Testfreigabe.
=> Entryform testerversion

src/components/TheEntryForm.vue
Dieser PR ergänzt auch noch das Auslesen des NMin für die Vorfrucht
=> nmin for vorfrucht

.eslintrc.cjs, package-lock.json, package.json, src/composables/useMap.js, src/composables/useTopicIntersections.js, src/constants.js
Zwecks Gleichziehen mit dem Agraratlas.
=> Use PMTiles, update OpenLayers

src/components/TheEntryForm.vue, src/components/TheFertilizerBalance.vue
Dieser PR zeigt im Bilanzfenster fehlende Eingabewerte. Außerdem wurde eine Anpassung bei einigen Eingabefeldern vorgenommen.
=> Bilanz showmissing

src/composables/useMap.js
Bessere Panning- und Selektionsperformance in Bereichen mit vielen Schlägen. Vor allem im Firefox.
=> Optimize for no overlaps

src/components/TheLoadSavePanel.vue
Dieser PR fixed fürs Erste das Problem mit dem Import / Export. Sollte aber noch auf UTF-8 Export umgestellt werden, wenn am Ende Zeit ist.
=> only quick fix for now

src/components/TheEntryForm.vue, src/composables/useBalanceCalculator.js, src/composables/useDataEntries.js
Dieser PR macht div. Änderungen nach der letzten ViKo bzw. Abstimmungen dazwischen. Die begonnene Bilanzerstellung ist nicht implementiert, da neue Spezifikationen folgen.
=> Vorfruchtwerte

src/components/TheEntryForm.vue, src/components/TheEntryList.vue, src/components/TheFertilizerBalance.vue, src/components/TheLoadSavePanel.vue, src/composables/useBalanceCalculator.js, src/composables/useDataEntries.js
Dieser PR ist eine erste Vollständige Umsetzung der Berechnungslogik. Außerdem werden verschiedene Features gemäß div. Issues umgesetzt. Für eine Update-Liste siehe #66
=> N abzuege neu

src/components/TheEntryForm.vue, src/components/TheFertilizerBalance.vue, src/composables/useBalanceCalculator.js
Dieser PR fügt auch die Gesamt-Netto-Düngeobergrenze an und re-installiert die Anzeige Nitratrisikogebiet Ja/Nein im Formular.
=> Re add nitratrisikogebiet inform

src/components/TheEntryForm.vue, src/components/TheFertilizerBalance.vue, src/composables/useBalanceCalculator.js, src/composables/useLookUps.js
Dieser PR bringt Updates und Bugfixes gemäß der ersten Test- / Feedback-Runde. Siehe Issues 97 - 110
=> Feedback updates 1

src/components/TheEntryForm.vue, src/composables/useBalanceCalculator.js
Dieser PR beseitigt einen schweren Fehler, das zu einer Dauerschleife und damit zum Absturz der Website geführt hat.
=> Bugfix infiniteloop

src/components/TheEntryForm.vue, src/components/TheFertilizerBalance.vue, src/composables/useBalanceCalculator.js, src/composables/useDataEntries.js
Dieser PR setzt div. Änderungen, Bugfixes und Ergänzungen aus offenen Issues um. Details in #66 nach Deploy.
=> Feedback updates 3

src/components/TheEntryForm.vue, src/components/TheFertilizerBalance.vue, src/composables/useBalanceCalculator.js
Dieser PR implementiert Teile der Logik neu, verhindert die Düngung ungenutzter Zwischenfrüchte und führt einen "Kopieren" Button ein.
=> Feedback update round 4

package-lock.json, package.json
Wichtigstes Dependency Update: die Ortssuche. Jetzt mit Hlifetext und übersichtlicheren sowie gefilterten Suchergebnissen.
=> Update engine version and dependencies

src/components/TheDisclaimer.vue, src/components/TheFertilizerBalance.vue, src/composables/useBalanceCalculator.js, src/views/MapView.vue
Dieser PR macht weitere kleine Bugfixes und implementiert einen Disclaimer.
=> More final treats

README.md, index.html
Für Zugriffsstatistiken mit Umami.
=> Allow to add tracker script from build-time env variable

index.html
Dieser Pull Request behebt das Problem, dass Browser versuchen, den Inhalt auf Deutsch übersetzen zu müssen.
=> Avoid client translation to German
